from commands import battery
from commands import battery
from commands import cpu
from commands import battery
from commands import cpu
from commands import process_control
from commands import system_exec
from CoreFunctions import cpu_brain
from CoreFunctions import system_monitor